title: Roselyne Laurent Architecte
author:
 name: Julien Dubuisson
 email: jdubuisson@users.noreply.github.com
 url: https://github.com/jdubuisson
metadata:
    description: 'Roselyne Laurent Architecte'

